import { model } from "@medusajs/framework/utils"
const TaxDetermination = model.define(
  { name: "tax_determination", tableName: "tax_determination" },
  {
    id: model.id({ prefix: "taxdet" }).primaryKey(),
    determination_reference: model.text().unique(),
    organisation_id: model.text().index().nullable(),
    customer_reference: model.text().index().nullable(),
    market_key: model.text(),
    legal_seller_key: model.text(),
    jurisdiction_key: model.text(),
    product_tax_classification: model.text(),
    transaction_type: model.text(),
    treatment: model.text(),
    currency_code: model.text(),
    taxable_basis_minor: model.bigNumber(),
    tax_amount_minor: model.bigNumber(),
    net_amount_minor: model.bigNumber(),
    gross_amount_minor: model.bigNumber(),
    price_display_mode: model.enum(["TAX_INCLUSIVE", "TAX_EXCLUSIVE"]),
    rate_basis_points: model.number(),
    rule_reference: model.text(),
    rule_version: model.text(),
    provider_key: model.text(),
    calculation_reference: model.text(),
    source_authority: model.text(),
    source_retrieved_at: model.dateTime(),
    legal_reason: model.text().nullable(),
    effective_at: model.dateTime(),
    source_idempotency_key: model.text().unique(),
    correlation_id: model.text(),
  },
)
export default TaxDetermination
