/**
 * The initial Thamani B2C retail catalogue (spec §15-22): ~38 products
 * across eight categories, sourced from Thamani's synthetic multi-supplier
 * network (`../suppliers/supplier-config.ts`), not a single default
 * supplier. Retail prices are independent per Market (spec §29: never
 * `za = ug * fx`) and carry no volume tiers or MOQ — this is single-unit
 * consumer retail, unlike the ZuriBeans wholesale catalogue.
 *
 * HS classification references, customs categories, and tax categories here
 * are illustrative reference data for exercising the commerce model. Spec
 * §17: "Validate precise customs classifications before final reference-data
 * seeding" remains outstanding and belongs to Gate 14 (Cross-Border Trade
 * Readiness), not this foundation slice.
 *
 * Two products are deliberately single-Market (`TH-LIF-001`, `TH-LIF-002`)
 * to exercise catalogue isolation between Uganda and South Africa ahead of
 * Gate 7 (Search) and Gate 90's acceptance tests.
 */
export type ThamaniProductCategory =
  | "COFFEE_TEA"
  | "CHOCOLATE_CONFECTIONERY"
  | "SPICES_SEASONINGS"
  | "PANTRY_STAPLES"
  | "NATURAL_FOODS"
  | "PERSONAL_CARE"
  | "HOUSEHOLD"
  | "LIFESTYLE"

export type ProductTaxCategory = "STANDARD" | "ZERO_RATED" | "EXEMPT"

export type RetailPrice = {
  currencyCode: "ugx" | "zar"
  standardAmount: number
}

export type FoodAttributes = {
  ingredients: string
  allergens: readonly string[]
  storageInstructions: string
  shelfLifeMonths: number
}

export type ThamaniMarketKey = "thamani_ug" | "thamani_za"

export type ThamaniProductConfig = {
  canonicalKey: string
  title: string
  handle: string
  sku: string
  category: ThamaniProductCategory
  supplierKey: string
  countryOfOrigin: string
  hsClassificationReference: string
  customsCategory: string
  productTaxCategory: ProductTaxCategory
  brand: string
  netWeightKg: number
  grossWeightKg: number
  packaging: string
  tradeUom: "EACH"
  consumerUom: string
  foodAttributes?: FoodAttributes
  eligibleMarkets: readonly ThamaniMarketKey[]
  prices: readonly RetailPrice[]
}

const BOTH_MARKETS: readonly ThamaniMarketKey[] = ["thamani_ug", "thamani_za"]

const price = (ugx: number, zar: number): readonly RetailPrice[] => [
  { currencyCode: "ugx", standardAmount: ugx },
  { currencyCode: "zar", standardAmount: zar },
]

const food = (
  ingredients: string,
  allergens: readonly string[],
  shelfLifeMonths: number,
  storageInstructions = "Store in a cool, dry place away from direct sunlight.",
): FoodAttributes => ({ ingredients, allergens, storageInstructions, shelfLifeMonths })

export const THAMANI_CATALOGUE: readonly ThamaniProductConfig[] = [
  // Coffee & Tea (6)
  {
    canonicalKey: "th-uganda-arabica-ground-coffee",
    title: "Uganda Arabica Ground Coffee 250g",
    handle: "thamani-uganda-arabica-ground-coffee-250g",
    sku: "TH-COF-001",
    category: "COFFEE_TEA",
    supplierKey: "sup_zuribeans_external",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-0901.21",
    customsCategory: "ROASTED_COFFEE",
    productTaxCategory: "STANDARD",
    brand: "Thamani Kitchen",
    netWeightKg: 0.25,
    grossWeightKg: 0.27,
    packaging: "Foil-lined stand-up pouch",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("100% roasted ground Arabica coffee.", [], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(18_000, 145),
  },
  {
    canonicalKey: "th-uganda-arabica-coffee-beans",
    title: "Uganda Arabica Coffee Beans 500g",
    handle: "thamani-uganda-arabica-coffee-beans-500g",
    sku: "TH-COF-002",
    category: "COFFEE_TEA",
    supplierKey: "sup_ug_mountain_roasters",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-0901.21",
    customsCategory: "ROASTED_COFFEE",
    productTaxCategory: "STANDARD",
    brand: "Mountain Peak",
    netWeightKg: 0.5,
    grossWeightKg: 0.53,
    packaging: "Foil-lined stand-up pouch with valve",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("100% roasted whole Arabica coffee beans.", [], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(32_000, 260),
  },
  {
    canonicalKey: "th-robusta-espresso-blend",
    title: "Robusta Espresso Blend 500g",
    handle: "thamani-robusta-espresso-blend-500g",
    sku: "TH-COF-003",
    category: "COFFEE_TEA",
    supplierKey: "sup_ug_mountain_roasters",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-0901.21",
    customsCategory: "ROASTED_COFFEE",
    productTaxCategory: "STANDARD",
    brand: "Mountain Peak",
    netWeightKg: 0.5,
    grossWeightKg: 0.53,
    packaging: "Foil-lined stand-up pouch with valve",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("Roasted Robusta and Arabica espresso blend.", [], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(30_000, 245),
  },
  {
    canonicalKey: "th-instant-coffee",
    title: "Instant Coffee 200g",
    handle: "thamani-instant-coffee-200g",
    sku: "TH-COF-004",
    category: "COFFEE_TEA",
    supplierKey: "sup_import_europe_fmcg",
    countryOfOrigin: "NL",
    hsClassificationReference: "HS-2101.11",
    customsCategory: "INSTANT_COFFEE_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Thamani Kitchen",
    netWeightKg: 0.2,
    grossWeightKg: 0.24,
    packaging: "Glass jar",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("100% freeze-dried instant coffee.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(22_000, 175),
  },
  {
    canonicalKey: "th-uganda-black-tea",
    title: "Uganda Black Tea 250g",
    handle: "thamani-uganda-black-tea-250g",
    sku: "TH-TEA-001",
    category: "COFFEE_TEA",
    supplierKey: "sup_ug_kampala_sme",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-0902.30",
    customsCategory: "BLACK_TEA",
    productTaxCategory: "STANDARD",
    brand: "Kampala Artisan",
    netWeightKg: 0.25,
    grossWeightKg: 0.27,
    packaging: "Carton box, 100 tagged sachets",
    tradeUom: "EACH",
    consumerUom: "BOX",
    foodAttributes: food("100% black tea leaf.", [], 18),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(9_000, 75),
  },
  {
    canonicalKey: "th-green-tea",
    title: "Green Tea 100g",
    handle: "thamani-green-tea-100g",
    sku: "TH-TEA-002",
    category: "COFFEE_TEA",
    supplierKey: "sup_import_indochina_provisions",
    countryOfOrigin: "VN",
    hsClassificationReference: "HS-0902.10",
    customsCategory: "GREEN_TEA_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Indochina Select",
    netWeightKg: 0.1,
    grossWeightKg: 0.12,
    packaging: "Carton box, 50 tagged sachets",
    tradeUom: "EACH",
    consumerUom: "BOX",
    foodAttributes: food("100% green tea leaf.", [], 18),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(14_000, 110),
  },

  // Chocolate & Confectionery (4)
  {
    canonicalKey: "th-dark-chocolate-70",
    title: "Dark Chocolate 70% 100g",
    handle: "thamani-dark-chocolate-70-100g",
    sku: "TH-CHO-001",
    category: "CHOCOLATE_CONFECTIONERY",
    supplierKey: "sup_import_south_america_cocoa",
    countryOfOrigin: "BR",
    hsClassificationReference: "HS-1806.32",
    customsCategory: "CHOCOLATE_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Thamani Kitchen",
    netWeightKg: 0.1,
    grossWeightKg: 0.11,
    packaging: "Foil wrap with paper sleeve",
    tradeUom: "EACH",
    consumerUom: "BAR",
    foodAttributes: food("Cocoa mass, cocoa butter, sugar (70% cocoa solids).", ["MILK_TRACE"], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(15_000, 120),
  },
  {
    canonicalKey: "th-milk-chocolate",
    title: "Milk Chocolate 100g",
    handle: "thamani-milk-chocolate-100g",
    sku: "TH-CHO-002",
    category: "CHOCOLATE_CONFECTIONERY",
    supplierKey: "sup_import_south_america_cocoa",
    countryOfOrigin: "BR",
    hsClassificationReference: "HS-1806.32",
    customsCategory: "CHOCOLATE_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Thamani Kitchen",
    netWeightKg: 0.1,
    grossWeightKg: 0.11,
    packaging: "Foil wrap with paper sleeve",
    tradeUom: "EACH",
    consumerUom: "BAR",
    foodAttributes: food("Cocoa mass, milk solids, cocoa butter, sugar.", ["MILK"], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(13_000, 105),
  },
  {
    canonicalKey: "th-cocoa-drinking-powder",
    title: "Cocoa Drinking Powder 400g",
    handle: "thamani-cocoa-drinking-powder-400g",
    sku: "TH-CHO-003",
    category: "CHOCOLATE_CONFECTIONERY",
    supplierKey: "sup_za_cape_fmcg",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-1806.90",
    customsCategory: "COCOA_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Cape FMCG Select",
    netWeightKg: 0.4,
    grossWeightKg: 0.44,
    packaging: "Metal tin",
    tradeUom: "EACH",
    consumerUom: "TIN",
    foodAttributes: food("Cocoa powder, sugar, milk solids.", ["MILK"], 18),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(21_000, 170),
  },
  {
    canonicalKey: "th-honey-confectionery",
    title: "Honey-Based Confectionery 150g",
    handle: "thamani-honey-confectionery-150g",
    sku: "TH-SWT-001",
    category: "CHOCOLATE_CONFECTIONERY",
    supplierKey: "sup_ug_elgon_agri",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-1704.90",
    customsCategory: "SUGAR_CONFECTIONERY",
    productTaxCategory: "STANDARD",
    brand: "Mount Elgon Cooperative",
    netWeightKg: 0.15,
    grossWeightKg: 0.16,
    packaging: "Resealable bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("Natural honey, sugar, roasted nuts.", ["TREE_NUTS"], 9),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(12_000, 95),
  },

  // Spices & Seasonings (5)
  {
    canonicalKey: "th-black-pepper-ground",
    title: "Black Pepper Ground 100g",
    handle: "thamani-black-pepper-ground-100g",
    sku: "TH-SPI-001",
    category: "SPICES_SEASONINGS",
    supplierKey: "sup_import_subcontinent_grains",
    countryOfOrigin: "IN",
    hsClassificationReference: "HS-0904.12",
    customsCategory: "SPICE_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Subcontinent Select",
    netWeightKg: 0.1,
    grossWeightKg: 0.12,
    packaging: "Glass jar with shaker lid",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("100% ground black pepper.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(8_000, 65),
  },
  {
    canonicalKey: "th-ginger-powder",
    title: "Ginger Powder 100g",
    handle: "thamani-ginger-powder-100g",
    sku: "TH-SPI-002",
    category: "SPICES_SEASONINGS",
    supplierKey: "sup_ug_savanna_foods",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-0910.11",
    customsCategory: "SPICE_LOCAL",
    productTaxCategory: "STANDARD",
    brand: "Savanna Foods",
    netWeightKg: 0.1,
    grossWeightKg: 0.12,
    packaging: "Glass jar with shaker lid",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("100% dried ground ginger.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(6_500, 55),
  },
  {
    canonicalKey: "th-vanilla-extract",
    title: "Vanilla Extract 100ml",
    handle: "thamani-vanilla-extract-100ml",
    sku: "TH-SPI-003",
    category: "SPICES_SEASONINGS",
    supplierKey: "sup_ug_elgon_agri",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-2106.90",
    customsCategory: "FLAVOURING_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Mount Elgon Cooperative",
    netWeightKg: 0.1,
    grossWeightKg: 0.13,
    packaging: "Amber glass bottle with dropper cap",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    foodAttributes: food(
      "Vanilla bean extract in alcohol and water. A distinct consumer product from whole cured vanilla pods.",
      [],
      24,
    ),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(25_000, 200),
  },
  {
    canonicalKey: "th-cinnamon-ground",
    title: "Cinnamon Ground 100g",
    handle: "thamani-cinnamon-ground-100g",
    sku: "TH-SPI-004",
    category: "SPICES_SEASONINGS",
    supplierKey: "sup_import_subcontinent_grains",
    countryOfOrigin: "IN",
    hsClassificationReference: "HS-0906.20",
    customsCategory: "SPICE_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Subcontinent Select",
    netWeightKg: 0.1,
    grossWeightKg: 0.12,
    packaging: "Glass jar with shaker lid",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("100% ground cinnamon.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(7_000, 58),
  },
  {
    canonicalKey: "th-turmeric-powder",
    title: "Turmeric Powder 100g",
    handle: "thamani-turmeric-powder-100g",
    sku: "TH-SPI-005",
    category: "SPICES_SEASONINGS",
    supplierKey: "sup_import_subcontinent_grains",
    countryOfOrigin: "IN",
    hsClassificationReference: "HS-0910.30",
    customsCategory: "SPICE_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Subcontinent Select",
    netWeightKg: 0.1,
    grossWeightKg: 0.12,
    packaging: "Glass jar with shaker lid",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("100% ground turmeric.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(6_000, 50),
  },

  // Pantry Staples (6)
  {
    canonicalKey: "th-white-rice",
    title: "White Rice 2kg",
    handle: "thamani-white-rice-2kg",
    sku: "TH-PAN-001",
    category: "PANTRY_STAPLES",
    supplierKey: "sup_import_subcontinent_grains",
    countryOfOrigin: "IN",
    hsClassificationReference: "HS-1006.30",
    customsCategory: "IMPORTED_STAPLE_GRAIN",
    productTaxCategory: "ZERO_RATED",
    brand: "Thamani Kitchen",
    netWeightKg: 2.0,
    grossWeightKg: 2.05,
    packaging: "Woven polypropylene bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("100% milled white rice.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(14_000, 110),
  },
  {
    canonicalKey: "th-wheat-flour",
    title: "Wheat Flour 2kg",
    handle: "thamani-wheat-flour-2kg",
    sku: "TH-PAN-002",
    category: "PANTRY_STAPLES",
    supplierKey: "sup_za_cape_fmcg",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-1101.00",
    customsCategory: "STAPLE_FLOUR",
    productTaxCategory: "ZERO_RATED",
    brand: "Cape FMCG Select",
    netWeightKg: 2.0,
    grossWeightKg: 2.05,
    packaging: "Paper bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("100% wheat flour.", ["GLUTEN"], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(11_000, 90),
  },
  {
    canonicalKey: "th-white-sugar",
    title: "White Sugar 2kg",
    handle: "thamani-white-sugar-2kg",
    sku: "TH-PAN-003",
    category: "PANTRY_STAPLES",
    supplierKey: "sup_ug_savanna_foods",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-1701.99",
    customsCategory: "STAPLE_SUGAR",
    productTaxCategory: "ZERO_RATED",
    brand: "Savanna Foods",
    netWeightKg: 2.0,
    grossWeightKg: 2.05,
    packaging: "Woven polypropylene bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("100% refined white sugar.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(10_000, 82),
  },
  {
    canonicalKey: "th-peanut-butter",
    title: "Peanut Butter 500g",
    handle: "thamani-peanut-butter-500g",
    sku: "TH-PAN-004",
    category: "PANTRY_STAPLES",
    supplierKey: "sup_ug_savanna_foods",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-2008.11",
    customsCategory: "PROCESSED_LEGUME_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Savanna Foods",
    netWeightKg: 0.5,
    grossWeightKg: 0.53,
    packaging: "Plastic jar",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("Roasted ground peanuts, salt.", ["PEANUTS"], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(13_000, 105),
  },
  {
    canonicalKey: "th-fruit-jam",
    title: "Fruit Jam 400g",
    handle: "thamani-fruit-jam-400g",
    sku: "TH-PAN-005",
    category: "PANTRY_STAPLES",
    supplierKey: "sup_ke_rift_wholesale",
    countryOfOrigin: "KE",
    hsClassificationReference: "HS-2007.99",
    customsCategory: "FRUIT_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Rift Valley Select",
    netWeightKg: 0.4,
    grossWeightKg: 0.44,
    packaging: "Glass jar",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("Mixed fruit, sugar, pectin.", [], 18),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(9_500, 78),
  },
  {
    canonicalKey: "th-cooking-oil",
    title: "Cooking Oil 2L",
    handle: "thamani-cooking-oil-2l",
    sku: "TH-PAN-006",
    category: "PANTRY_STAPLES",
    supplierKey: "sup_import_europe_fmcg",
    countryOfOrigin: "NL",
    hsClassificationReference: "HS-1512.19",
    customsCategory: "IMPORTED_VEGETABLE_OIL",
    productTaxCategory: "STANDARD",
    brand: "Thamani Kitchen",
    netWeightKg: 2.0,
    grossWeightKg: 2.1,
    packaging: "PET bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    foodAttributes: food("100% refined sunflower oil.", [], 18),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(26_000, 210),
  },

  // Natural Foods (4)
  {
    canonicalKey: "th-natural-honey",
    title: "Natural Honey 500g",
    handle: "thamani-natural-honey-500g",
    sku: "TH-NAT-001",
    category: "NATURAL_FOODS",
    supplierKey: "sup_ug_elgon_agri",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-0409.00",
    customsCategory: "NATURAL_HONEY",
    productTaxCategory: "ZERO_RATED",
    brand: "Mount Elgon Cooperative",
    netWeightKg: 0.5,
    grossWeightKg: 0.55,
    packaging: "Glass jar",
    tradeUom: "EACH",
    consumerUom: "JAR",
    foodAttributes: food("100% natural honey.", [], 24),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(18_000, 145),
  },
  {
    canonicalKey: "th-dried-mixed-fruit",
    title: "Dried Mixed Fruit 200g",
    handle: "thamani-dried-mixed-fruit-200g",
    sku: "TH-NAT-002",
    category: "NATURAL_FOODS",
    supplierKey: "sup_za_winelands_agri",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-0813.50",
    customsCategory: "DRIED_FRUIT",
    productTaxCategory: "STANDARD",
    brand: "Winelands Select",
    netWeightKg: 0.2,
    grossWeightKg: 0.21,
    packaging: "Resealable bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("Dried apricot, raisin, fig, and prune mix.", ["SULPHITES"], 9),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(12_000, 95),
  },
  {
    canonicalKey: "th-mixed-nuts",
    title: "Mixed Nuts 250g",
    handle: "thamani-mixed-nuts-250g",
    sku: "TH-NAT-003",
    category: "NATURAL_FOODS",
    supplierKey: "sup_za_winelands_agri",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-2008.19",
    customsCategory: "PREPARED_NUTS",
    productTaxCategory: "STANDARD",
    brand: "Winelands Select",
    netWeightKg: 0.25,
    grossWeightKg: 0.26,
    packaging: "Resealable bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("Roasted cashew, almond, and macadamia mix.", ["TREE_NUTS"], 9),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(16_000, 130),
  },
  {
    canonicalKey: "th-raw-cocoa-nibs",
    title: "Raw Cocoa Nibs 200g",
    handle: "thamani-raw-cocoa-nibs-200g",
    sku: "TH-NAT-004",
    category: "NATURAL_FOODS",
    supplierKey: "sup_import_south_america_cocoa",
    countryOfOrigin: "BR",
    hsClassificationReference: "HS-1801.00",
    customsCategory: "RAW_COCOA_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Thamani Kitchen",
    netWeightKg: 0.2,
    grossWeightKg: 0.21,
    packaging: "Resealable bag",
    tradeUom: "EACH",
    consumerUom: "BAG",
    foodAttributes: food("100% crushed raw cocoa beans.", [], 12),
    eligibleMarkets: BOTH_MARKETS,
    prices: price(14_000, 115),
  },

  // Personal Care (5)
  {
    canonicalKey: "th-body-lotion",
    title: "Body Lotion 400ml",
    handle: "thamani-body-lotion-400ml",
    sku: "TH-PC-001",
    category: "PERSONAL_CARE",
    supplierKey: "sup_za_karoo_naturals",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-3304.99",
    customsCategory: "COSMETIC_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Karoo Naturals",
    netWeightKg: 0.4,
    grossWeightKg: 0.44,
    packaging: "Pump-top plastic bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(24_000, 195),
  },
  {
    canonicalKey: "th-natural-soap-bar",
    title: "Natural Soap Bar 150g",
    handle: "thamani-natural-soap-bar-150g",
    sku: "TH-PC-002",
    category: "PERSONAL_CARE",
    supplierKey: "sup_ug_entebbe_personal_care",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-3401.11",
    customsCategory: "TOILET_SOAP",
    productTaxCategory: "STANDARD",
    brand: "Entebbe Naturals",
    netWeightKg: 0.15,
    grossWeightKg: 0.16,
    packaging: "Paper wrap",
    tradeUom: "EACH",
    consumerUom: "BAR",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(6_000, 48),
  },
  {
    canonicalKey: "th-shampoo",
    title: "Shampoo 400ml",
    handle: "thamani-shampoo-400ml",
    sku: "TH-PC-003",
    category: "PERSONAL_CARE",
    supplierKey: "sup_za_karoo_naturals",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-3305.10",
    customsCategory: "HAIR_CARE_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Karoo Naturals",
    netWeightKg: 0.4,
    grossWeightKg: 0.44,
    packaging: "Pump-top plastic bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(19_000, 155),
  },
  {
    canonicalKey: "th-hair-conditioner",
    title: "Hair Conditioner 400ml",
    handle: "thamani-hair-conditioner-400ml",
    sku: "TH-PC-004",
    category: "PERSONAL_CARE",
    supplierKey: "sup_za_karoo_naturals",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-3305.90",
    customsCategory: "HAIR_CARE_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Karoo Naturals",
    netWeightKg: 0.4,
    grossWeightKg: 0.44,
    packaging: "Pump-top plastic bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(19_000, 155),
  },
  {
    canonicalKey: "th-natural-skin-oil",
    title: "Natural Skin Oil 100ml",
    handle: "thamani-natural-skin-oil-100ml",
    sku: "TH-PC-005",
    category: "PERSONAL_CARE",
    supplierKey: "sup_ug_entebbe_personal_care",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-3304.99",
    customsCategory: "COSMETIC_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Entebbe Naturals",
    netWeightKg: 0.1,
    grossWeightKg: 0.12,
    packaging: "Glass dropper bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(21_000, 170),
  },

  // Household (4)
  {
    canonicalKey: "th-dishwashing-liquid",
    title: "Dishwashing Liquid 500ml",
    handle: "thamani-dishwashing-liquid-500ml",
    sku: "TH-HH-001",
    category: "HOUSEHOLD",
    supplierKey: "sup_ug_nile_household",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-3402.20",
    customsCategory: "HOUSEHOLD_CLEANING_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Nile Household",
    netWeightKg: 0.5,
    grossWeightKg: 0.53,
    packaging: "Flip-top plastic bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(9_000, 72),
  },
  {
    canonicalKey: "th-laundry-detergent",
    title: "Laundry Detergent 1kg",
    handle: "thamani-laundry-detergent-1kg",
    sku: "TH-HH-002",
    category: "HOUSEHOLD",
    supplierKey: "sup_za_durban_household",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-3402.20",
    customsCategory: "HOUSEHOLD_CLEANING_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Durban Household",
    netWeightKg: 1.0,
    grossWeightKg: 1.05,
    packaging: "Cardboard box",
    tradeUom: "EACH",
    consumerUom: "BOX",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(15_000, 120),
  },
  {
    canonicalKey: "th-household-cleaner",
    title: "Household Cleaner 750ml",
    handle: "thamani-household-cleaner-750ml",
    sku: "TH-HH-003",
    category: "HOUSEHOLD",
    supplierKey: "sup_za_durban_household",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-3402.90",
    customsCategory: "HOUSEHOLD_CLEANING_PREPARATION",
    productTaxCategory: "STANDARD",
    brand: "Durban Household",
    netWeightKg: 0.75,
    grossWeightKg: 0.79,
    packaging: "Trigger-spray plastic bottle",
    tradeUom: "EACH",
    consumerUom: "BOTTLE",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(12_000, 95),
  },
  {
    canonicalKey: "th-reusable-food-storage-set",
    title: "Reusable Food-Storage Container Set",
    handle: "thamani-reusable-food-storage-container-set",
    sku: "TH-HH-004",
    category: "HOUSEHOLD",
    supplierKey: "sup_ug_nile_household",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-3924.10",
    customsCategory: "PLASTIC_HOUSEWARE",
    productTaxCategory: "STANDARD",
    brand: "Nile Household",
    netWeightKg: 0.4,
    grossWeightKg: 0.45,
    packaging: "Retail carton, set of 4",
    tradeUom: "EACH",
    consumerUom: "SET",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(25_000, 200),
  },

  // Lifestyle / Miscellaneous (4) — includes the two deliberate single-Market SKUs.
  {
    canonicalKey: "th-reusable-cotton-tote-bag",
    title: "Reusable Cotton Tote Bag",
    handle: "thamani-reusable-cotton-tote-bag",
    sku: "TH-LIF-001",
    category: "LIFESTYLE",
    supplierKey: "sup_ug_kampala_sme",
    countryOfOrigin: "UG",
    hsClassificationReference: "HS-4202.92",
    customsCategory: "TEXTILE_ACCESSORY",
    productTaxCategory: "STANDARD",
    brand: "Kampala Artisan",
    netWeightKg: 0.15,
    grossWeightKg: 0.16,
    packaging: "Recycled paper band",
    tradeUom: "EACH",
    consumerUom: "EACH",
    // Uganda-only: locally made and not yet cleared for cross-border retail
    // export to South Africa. Exercises catalogue isolation (spec §36, §90).
    eligibleMarkets: ["thamani_ug"],
    prices: price(15_000, 120),
  },
  {
    canonicalKey: "th-handcrafted-ceramic-mug",
    title: "Handcrafted Ceramic Mug",
    handle: "thamani-handcrafted-ceramic-mug",
    sku: "TH-LIF-002",
    category: "LIFESTYLE",
    supplierKey: "sup_za_joburg_sme",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-6912.00",
    customsCategory: "CERAMIC_HOUSEWARE",
    productTaxCategory: "STANDARD",
    brand: "Johannesburg Home Crafts",
    netWeightKg: 0.35,
    grossWeightKg: 0.4,
    packaging: "Protective carton insert",
    tradeUom: "EACH",
    consumerUom: "EACH",
    // South Africa-only: locally made and not yet cleared for cross-border
    // retail export to Uganda. Exercises catalogue isolation (spec §36, §90).
    eligibleMarkets: ["thamani_za"],
    prices: price(22_000, 180),
  },
  {
    canonicalKey: "th-insulated-water-bottle",
    title: "Insulated Stainless Water Bottle 750ml",
    handle: "thamani-insulated-stainless-water-bottle-750ml",
    sku: "TH-LIF-003",
    category: "LIFESTYLE",
    supplierKey: "sup_import_europe_fmcg",
    countryOfOrigin: "NL",
    hsClassificationReference: "HS-9617.00",
    customsCategory: "VACUUM_FLASK_IMPORTED",
    productTaxCategory: "STANDARD",
    brand: "Thamani Living",
    netWeightKg: 0.4,
    grossWeightKg: 0.45,
    packaging: "Retail carton",
    tradeUom: "EACH",
    consumerUom: "EACH",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(35_000, 280),
  },
  {
    canonicalKey: "th-scented-soy-candle",
    title: "Scented Soy Candle",
    handle: "thamani-scented-soy-candle",
    sku: "TH-LIF-004",
    category: "LIFESTYLE",
    supplierKey: "sup_za_cape_fmcg",
    countryOfOrigin: "ZA",
    hsClassificationReference: "HS-3406.00",
    customsCategory: "CANDLE",
    productTaxCategory: "STANDARD",
    brand: "Cape FMCG Select",
    netWeightKg: 0.3,
    grossWeightKg: 0.35,
    packaging: "Glass jar with lid",
    tradeUom: "EACH",
    consumerUom: "EACH",
    eligibleMarkets: BOTH_MARKETS,
    prices: price(18_000, 145),
  },
]

export const THAMANI_CATEGORY_COUNTS: Readonly<Record<ThamaniProductCategory, number>> = {
  COFFEE_TEA: 6,
  CHOCOLATE_CONFECTIONERY: 4,
  SPICES_SEASONINGS: 5,
  PANTRY_STAPLES: 6,
  NATURAL_FOODS: 4,
  PERSONAL_CARE: 5,
  HOUSEHOLD: 4,
  LIFESTYLE: 4,
}
